### ISSUE TITLE
Add support for fetch filter

### ISSUE THREAD

**Issue by guzman-raphael** [datajoint/DJ-GUI-React#43]
Proceed with design flow `B`:
![image](https://user-images.githubusercontent.com/38401847/107285468-d764b380-6a24-11eb-8433-1959d4b1cf55.png)

Supported inputs should be:
- enabled
- inverse
- attribute name
- operation
  - equal, requires 1 value
  - greater than, requires 1 value
  - less than, requires 1 value
  - between, requires 2 values
  - like, requires 1 value
  - in, requires many values

**Comment by Synicix** [comment]
Discussed with Raphael to respec it to what is the minmumly require

=
<
>
>=
<=

is, like, between will be implmemented later.

Check DJ_API for the rest of the details on the backend
